---
- name: prometheus-exporter - node-exporter - create user
  user:
    name: node_exporter
    shell: /usr/sbin/nologin
  become: true

- name: prometheus-exporter - node-exporter - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: node_exporter
    group: node_exporter
    mode: 0750
  become: true
  with_items:
    - "{{ prometheus_exporter_textfile_directory }}"

# smartmon

- name: prometheus-exporter - node-exporter(smartmon) - install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ required_packages_prometheus_exporter_smartmon }}"
  when:
    - prometheus_exporter_smartmon_enable|bool
    - prometheus_exporter_smartmon_groupname in group_names or prometheus_exporter_smartmon_groupname == 'all'

- name: prometheus-exporter - node-exporter(smartmon) - copy script
  copy:
    src: node-exporter/node_exporter-smartmon
    dest: /usr/sbin/node_exporter-smartmon
    owner: root
    group: root
    mode: 0755
  become: true
  when:
    - prometheus_exporter_smartmon_enable|bool
    - prometheus_exporter_smartmon_groupname in group_names or prometheus_exporter_smartmon_groupname == 'all'

- name: prometheus-exporter - node-exporter(smartmon) - create cronjob
  cron:
    name: node_exporter-smartmon
    minute: "{{ prometheus_exporter_smartmon_minute }}"
    user: root
    job: "/usr/sbin/node_exporter-smartmon > {{ prometheus_exporter_textfile_directory }}/node_exporter-smartmon.prom"
    cron_file: node_exporter-smartmon
  become: true
  when:
    - prometheus_exporter_smartmon_enable|bool
    - prometheus_exporter_smartmon_groupname in group_names or prometheus_exporter_smartmon_groupname == 'all'

# ipmitool

- name: prometheus-exporter - node-exporter(ipmitool) - install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ required_packages_prometheus_exporter_ipmitool }}"
  when:
    - prometheus_exporter_ipmitool_enable|bool
    - prometheus_exporter_ipmitool_groupname in group_names or prometheus_exporter_ipmitool_groupname == 'all'

- name: prometheus-exporter - node-exporter(ipmitool) - enable required modules
  lineinfile:
    line: "{{ item }}"
    state: present
    dest: /etc/modules
  become: true
  with_items: "{{ required_modules_prometheus_exporter_ipmitool }}"
  when:
    - prometheus_exporter_ipmitool_enable|bool
    - prometheus_exporter_ipmitool_groupname in group_names or prometheus_exporter_ipmitool_groupname == 'all'

- name: prometheus-exporter - node-exporter(ipmitool) - load required modules
  modprobe:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ required_modules_prometheus_exporter_ipmitool }}"
  when:
    - prometheus_exporter_ipmitool_enable|bool
    - prometheus_exporter_ipmitool_groupname in group_names or prometheus_exporter_ipmitool_groupname == 'all'

- name: prometheus-exporter - node-exporter(ipmitool) - copy script
  copy:
    src: node-exporter/node_exporter-ipmitool
    dest: /usr/sbin/node_exporter-ipmitool
    owner: root
    group: root
    mode: 0755
  become: true
  when:
    - prometheus_exporter_ipmitool_enable|bool
    - prometheus_exporter_ipmitool_groupname in group_names or prometheus_exporter_ipmitool_groupname == 'all'

- name: prometheus-exporter - node-exporter(ipmitool) - create cronjob
  cron:
    name: node_exporter-ipmitool
    minute: "{{ prometheus_exporter_ipmitool_minute }}"
    user: root
    job: "ipmitool sensor | awk -f /usr/sbin/node_exporter-ipmitool > {{ prometheus_exporter_textfile_directory }}/node_exporter-ipmitool.prom"
    cron_file: node_exporter-ipmitool
  become: true
  when:
    - prometheus_exporter_ipmitool_enable|bool
    - prometheus_exporter_ipmitool_groupname in group_names or prometheus_exporter_ipmitool_groupname == 'all'

# node-exporter

- name: prometheus-exporter - node-exporter - copy binary
  copy:
    src: node-exporter/node_exporter
    dest: /usr/sbin/node_exporter
    owner: root
    group: root
    mode: 0755
  become: true
  notify: Restart node_exporter service

- name: prometheus-exporter - node-exporter - copy service file
  copy:
    src: node-exporter/node_exporter.service
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  become: true
  notify: Restart node_exporter service

- name: prometheus-exporter - node-exporter - copy defaults file
  template:
    src: node-exporter/node_exporter.defaults.j2
    dest: /etc/default/node_exporter
    owner: root
    group: root
    mode: 0644
  become: true
  notify: Restart node_exporter service

- name: prometheus-exporter - node-exporter - enable/start service
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes
  become: true
