---
- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  become: true
  with_items:
    - "{{ prometheus_exporter_docker_compose_directory }}"
    - "{{ prometheus_exporter_configuration_directory }}"

- name: ceph - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  become: true
  with_items:
    - "{{ prometheus_exporter_configuration_directory }}/ceph"
  when:
    - prometheus_exporter_ceph_enable|bool
    - prometheus_exporter_ceph_groupname in group_names

- name: ceph - copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ prometheus_exporter_configuration_directory }}/{{ item.dest }}"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640
  with_items:
    - src: ceph/ceph.conf.j2
      dest: ceph/ceph.conf
  notify: Restart service
  when:
    - prometheus_exporter_ceph_enable|bool
    - prometheus_exporter_ceph_groupname in group_names

- name: ceph - copy keyring file
  copy:
    src: "{{ prometheus_exporter_ceph_keyring_path }}"
    dest: "{{ prometheus_exporter_configuration_directory }}/ceph/{{ prometheus_exporter_ceph_keyring_path|basename }}"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640
  notify: Restart service
  when:
    - prometheus_exporter_ceph_enable|bool
    - prometheus_exporter_ceph_groupname in group_names

- name: mariadb - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  become: true
  with_items:
    - "{{ prometheus_exporter_configuration_directory }}/mariadb"
  when:
    - prometheus_exporter_mariadb_enable|bool
    - prometheus_exporter_mariadb_groupname in group_names

- name: mariadb - copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ prometheus_exporter_configuration_directory }}/{{ item.dest }}"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640
  with_items:
    - src: mariadb/my.cnf.j2
      dest: mariadb/my.cnf
  notify: Restart service
  when:
    - prometheus_exporter_mariadb_enable|bool
    - prometheus_exporter_mariadb_groupname in group_names

- name: nginx - install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - python-passlib
  when: prometheus_exporter_nginx_authentication

- name: prometheus-exporter - nginx - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  become: true
  with_items:
    - "{{ prometheus_exporter_configuration_directory }}/nginx"

- name: nginx - prepare auth file
  htpasswd:
    path: "{{ prometheus_exporter_configuration_directory }}/nginx/htpasswd.nginx"
    name: "{{ prometheus_exporter_nginx_username }}"
    password: "{{ prometheus_exporter_nginx_password }}"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640
  when: prometheus_exporter_nginx_authentication

- name: nginx - copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ prometheus_exporter_configuration_directory }}/{{ item.dest }}"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640
  notify: Restart service
  with_items:
    - src: nginx/nginx.conf.j2
      dest: nginx/nginx.conf

- name: cadvisor - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  become: true
  with_items:
    - "{{ prometheus_exporter_configuration_directory }}/cadvisor"
  when:
    - prometheus_exporter_cadvisor_enable|bool
    - prometheus_exporter_cadvisor_enable_webinterface|bool
    - (prometheus_exporter_cadvisor_groupname in group_names or prometheus_exporter_cadvisor_groupname == 'all')

- name: cadvisor - prepare auth file
  htpasswd:
    path: "{{ prometheus_exporter_configuration_directory }}/cadvisor/htpasswd.cadvisor"
    name: "{{ prometheus_exporter_cadvisor_username }}"
    password: "{{ prometheus_exporter_cadvisor_password }}"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640
  when:
    - prometheus_exporter_cadvisor_enable|bool
    - prometheus_exporter_cadvisor_enable_webinterface|bool
    - (prometheus_exporter_cadvisor_groupname in group_names or prometheus_exporter_cadvisor_groupname == 'all')

- name: Copy docker-compose.yml file
  template:
    src: docker-compose.yml.j2
    dest: "{{ prometheus_exporter_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640

- name: Pull images
  command: "docker-compose -f {{ prometheus_exporter_docker_compose_directory }}/docker-compose.yml pull"
  register: result
  changed_when: ('Downloaded' in result.stdout)

- name: Run service
  command: "docker-compose -f {{ prometheus_exporter_docker_compose_directory }}/docker-compose.yml up -d --remove-orphans --no-build"
  register: result
  changed_when: ('Creating' in result.stdout or 'Recreating' in result.stdout)
