---
- name: prometheus-exporter - install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ required_packages_prometheus_exporter }}"

- name: prometheus-exporter - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  become: true
  with_items:
    - "{{ prometheus_exporter_docker_compose_directory }}"
    - "{{ prometheus_exporter_configuration_directory }}"

- name: prometheus-exporter - create required directories (mariadb)
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  become: true
  with_items:
    - "{{ prometheus_exporter_configuration_directory }}/mariadb"
  when:
    - prometheus_exporter_mariadb_enable|bool
    - prometheus_exporter_mariadb_groupname in group_names

- name: prometheus-exporter - mariadb - copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ prometheus_exporter_configuration_directory }}/{{ item.dest }}"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640
  with_items:
    - src: mariadb/my.cnf.j2
      dest: mariadb/my.cnf
  when:
    - prometheus_exporter_mariadb_enable|bool
    - prometheus_exporter_mariadb_groupname in group_names

- name: prometheus-exporter - cadvisor - install required packages
  package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - python-passlib
  when:
    - prometheus_exporter_cadvisor_enable|bool
    - (prometheus_exporter_cadvisor_groupname in group_names or prometheus_exporter_cadvisor_groupname == 'all')

- name: prometheus-exporter - cadvisor - create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0750
  become: true
  with_items:
    - "{{ prometheus_exporter_configuration_directory }}/cadvisor"
  when:
    - prometheus_exporter_cadvisor_enable|bool
    - (prometheus_exporter_cadvisor_groupname in group_names or prometheus_exporter_cadvisor_groupname == 'all')

- name: prometheus-exporter - cadvisor - prepare auth file
  htpasswd:
    path: "{{ prometheus_exporter_configuration_directory }}/cadvisor/htpasswd.cadvisor"
    name: "{{ prometheus_exporter_cadvisor_username }}"
    password: "{{ prometheus_exporter_cadvisor_password }}"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640
  when:
    - prometheus_exporter_cadvisor_enable|bool
    - (prometheus_exporter_cadvisor_groupname in group_names or prometheus_exporter_cadvisor_groupname == 'all')

- name: prometheus-exporter - copy docker-compose.yml file
  template:
    src: docker-compose.yml.j2
    dest: "{{ prometheus_exporter_docker_compose_directory }}/docker-compose.yml"
    owner: "{{ operator_user }}"
    group: "{{ operator_group }}"
    mode: 0640

- name: prometheus-exporter - run exporter services
  docker_service:
    project_name: prometheus-exporter
    project_src: "{{ prometheus_exporter_docker_compose_directory }}"
    pull: yes
