---
- name: Restart node_exporter service
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes
  become: true

- name: Restart service
  command: "docker-compose -f {{ prometheus_exporter_docker_compose_directory }}/docker-compose.yml restart"
