---
- name: Restart node_exporter service
  systemd:
    name: node_exporter
    state: restarted
    daemon_reload: yes

- name: Restart service
  docker_service:
    project_name: prometheus-exporter
    project_src: "{{ prometheus_exporter_docker_compose_directory }}"
    restarted: true
