---
- name: Playbook for role testing
  hosts: all
  connection: paramiko

  vars:
    docker_registry: registry-1.osism.io
    operator_user: ubuntu
    prometheus_exporter_ipmitool_enable: no

  roles:
    - role: ansible-prometheus-exporter
